/**
 * Eligibility data — which postcodes count as specified work, for which industry.
 *
 * Generated by pipeline/extract_eligibility.py straight from the Home Affairs
 * PDF and validated against the 2,641 real ABS postal areas. Nothing here is
 * hand-maintained; to change it, re-run the pipeline.
 */

import type { VisaSubclass } from "./config.ts";

export interface AreaData {
  label: string;
  postcodes: string[];
  count: number;
  by_state: Record<string, string[]>;
}

export interface IndustryData {
  label: string;
  /** Designated areas this industry may be performed in, or ["anywhere"]. */
  areas: string[];
  note: string | null;
}

export interface EligibilityData {
  visa: string;
  generated: string;
  source: {
    publisher: string;
    document: string;
    page_last_updated: string;
    sha256: string;
    retrieved: string;
  };
  areas: Record<string, AreaData>;
  industries: Record<string, IndustryData>;
}

/**
 * Loaded datasets, keyed by visa subclass. 417 is expected to be missing until
 * its source document is obtained — the UI must say so rather than imply the
 * answer is "not eligible".
 */
const cache = new Map<VisaSubclass, EligibilityData | null>();

export async function loadEligibility(
  visa: VisaSubclass,
  baseUrl: string,
): Promise<EligibilityData | null> {
  const hit = cache.get(visa);
  if (hit !== undefined) return hit;

  try {
    const res = await fetch(`${baseUrl}data/eligibility_${visa}.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = (await res.json()) as EligibilityData;
    cache.set(visa, data);
    return data;
  } catch {
    // Missing data is a real state, not an error to swallow silently: the caller
    // renders "no data for this visa" instead of an empty (= ineligible) map.
    cache.set(visa, null);
    return null;
  }
}

/** The set of postcodes where a given industry counts. */
export function postcodesForIndustry(
  data: EligibilityData,
  industryKey: string,
): { postcodes: string[]; anywhere: boolean } {
  const industry = data.industries[industryKey];
  if (!industry) return { postcodes: [], anywhere: false };
  if (industry.areas.includes("anywhere")) return { postcodes: [], anywhere: true };

  const out = new Set<string>();
  for (const areaKey of industry.areas) {
    const area = data.areas[areaKey];
    if (!area) continue;
    for (const pc of area.postcodes) out.add(pc);
  }
  return { postcodes: [...out].sort(), anywhere: false };
}

/** Which designated areas a postcode belongs to. */
export function areasForPostcode(data: EligibilityData, postcode: string): string[] {
  return Object.entries(data.areas)
    .filter(([, area]) => area.postcodes.includes(postcode))
    .map(([key]) => key);
}

/** Which industries may be performed in a postcode, with the reason. */
export function industriesForPostcode(
  data: EligibilityData,
  postcode: string,
): { key: string; label: string; via: string[] }[] {
  const areas = new Set(areasForPostcode(data, postcode));
  const out: { key: string; label: string; via: string[] }[] = [];

  for (const [key, industry] of Object.entries(data.industries)) {
    if (industry.areas.includes("anywhere")) {
      out.push({ key, label: industry.label, via: ["anywhere in Australia"] });
      continue;
    }
    const via = industry.areas.filter((a) => areas.has(a));
    if (via.length > 0) {
      out.push({
        key,
        label: industry.label,
        via: via.map((a) => data.areas[a]?.label ?? a),
      });
    }
  }
  return out;
}
